# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 14:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('carry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='任务编号')),
                ('title', models.CharField(max_length=128, verbose_name='任务名称')),
                ('introduction_content', models.TextField(verbose_name='任务来源，介绍，以及完成方法')),
                ('status',
                 models.IntegerField(choices=[(1, '已经完成'), (2, '还未完成'), (3, '有困难'), (4, '超期'), (5, '延期')], default=2,
                                     verbose_name='任务状态')),
                ('creat_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('wish_finish_time', models.DateTimeField(blank=True, null=True, verbose_name='预计完成时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('finish_content', models.TextField(blank=True, null=True, verbose_name='完成内容：请填写完成的方式，以及生成物')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user',
                                                to='carry.User', verbose_name='任务来源')),
                ('reply',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task',
                                   verbose_name='关联上级任务')),
                ('to_user', models.ManyToManyField(related_name='to_user', to='carry.User', verbose_name='任务接收')),
            ],
        ),
    ]
