# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 01:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('task', '0002_auto_20180311_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='任务类型编号')),
                ('title', models.CharField(max_length=128, verbose_name='类型名称')),
                ('score', models.CharField(max_length=128, verbose_name='获得分数')),
                ('diff_level', models.CharField(max_length=128, verbose_name='难易程度')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='finish_cost_time',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='任务花费时间，请填写小时'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='finish_Fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='task.TaskType', verbose_name='选择完成的类型'),
        ),
    ]
