# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carry', '0001_initial'),
        ('task', '0003_auto_20180312_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='to_user',
        ),
        migrations.AddField(
            model_name='task',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='carry.User', verbose_name='任务接收'),
            preserve_default=False,
        ),
    ]
